package org.irri.iric.portal.genotype.views;

import javax.persistence.Entity;
import javax.persistence.Id;





// Generated Jun 27, 2014 8:48:08 PM by Hibernate Tools 3.4.0.CR1

/**
 * Snp2lines generated by hbm2java
 */
@Entity
public class Snp2lines implements java.io.Serializable {

	@Id
	private Snp2linesId id;

	public Snp2lines() {
	}

	public Snp2lines(Snp2linesId id) {
		this.id = id;
	}

	public Snp2linesId getId() {
		return this.id;
	}

	public void setId(Snp2linesId id) {
		this.id = id;
	}

}
