package org.irri.iric.portal.genotype.views;

// Generated Jul 31, 2014 6:00:11 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;

/**
 * ViewCount2linesMismatchId generated by hbm2java
 */
@Entity @IdClass(ViewCount2linesMismatchId.class)
public class ViewCount2linesMismatchId implements java.io.Serializable {

	@Id
	private String var1;
	@Id
	private String var2;
	@Id
	private BigDecimal mismatch;

	public ViewCount2linesMismatchId() {
	}

	public ViewCount2linesMismatchId(String var1, String var2,
			BigDecimal mismatch) {
		this.var1 = var1;
		this.var2 = var2;
		this.mismatch = mismatch;
	}

	public String getVar1() {
		return this.var1;
	}

	public void setVar1(String var1) {
		this.var1 = var1;
	}

	public String getVar2() {
		return this.var2;
	}

	public void setVar2(String var2) {
		this.var2 = var2;
	}

	public BigDecimal getMismatch() {
		return this.mismatch;
	}

	public void setMismatch(BigDecimal mismatch) {
		this.mismatch = mismatch;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewCount2linesMismatchId))
			return false;
		ViewCount2linesMismatchId castOther = (ViewCount2linesMismatchId) other;

		return ((this.getVar1() == castOther.getVar1()) || (this.getVar1() != null
				&& castOther.getVar1() != null && this.getVar1().equals(
				castOther.getVar1())))
				&& ((this.getVar2() == castOther.getVar2()) || (this.getVar2() != null
						&& castOther.getVar2() != null && this.getVar2()
						.equals(castOther.getVar2())))
				&& ((this.getMismatch() == castOther.getMismatch()) || (this
						.getMismatch() != null
						&& castOther.getMismatch() != null && this
						.getMismatch().equals(castOther.getMismatch())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getVar1() == null ? 0 : this.getVar1().hashCode());
		result = 37 * result
				+ (getVar2() == null ? 0 : this.getVar2().hashCode());
		result = 37 * result
				+ (getMismatch() == null ? 0 : this.getMismatch().hashCode());
		return result;
	}

}
