package org.irri.iric.portal.genotype.views;

// Generated Jul 22, 2014 8:45:17 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;

import org.irri.iric.portal.domain.SnpsAllvarsRefMismatch;

/**
 * ViewCountVarrefMismatchId generated by hbm2java
 */
@Entity @IdClass(ViewCountVarrefMismatchId.class)
public class ViewCountVarrefMismatchId   implements java.io.Serializable,  SnpsAllvarsRefMismatch {

	@Id
	private String varname;
	@Id
	private BigDecimal mismatch;

	public ViewCountVarrefMismatchId() {
	}

	public ViewCountVarrefMismatchId(String varname, BigDecimal mismatch) {
		this.varname = varname;
		this.mismatch = mismatch;
	}

	public String getVarname() {
		return this.varname;
	}

	public void setVarname(String varname) {
		this.varname = varname;
	}

	public BigDecimal getMismatch() {
		return this.mismatch;
	}

	public void setMismatch(BigDecimal mismatch) {
		this.mismatch = mismatch;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewCountVarrefMismatchId))
			return false;
		ViewCountVarrefMismatchId castOther = (ViewCountVarrefMismatchId) other;

		return ((this.getVarname() == castOther.getVarname()) || (this
				.getVarname() != null && castOther.getVarname() != null && this
				.getVarname().equals(castOther.getVarname())))
				&& ((this.getMismatch() == castOther.getMismatch()) || (this
						.getMismatch() != null
						&& castOther.getMismatch() != null && this
						.getMismatch().equals(castOther.getMismatch())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getVarname() == null ? 0 : this.getVarname().hashCode());
		result = 37 * result
				+ (getMismatch() == null ? 0 : this.getMismatch().hashCode());
		return result;
	}

	@Override
	public Integer getVar() {
		// TODO Auto-generated method stub
		return varname;
	}
	
	

}
