package org.irri.iric.portal.genotype.views;

import javax.persistence.Entity;
import javax.persistence.Id;

// Generated Jul 10, 2014 12:01:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * ViewSnpAllvars generated by hbm2java
 */
@Entity
public class ViewSnpAllvars implements java.io.Serializable {

	@Id
	private ViewSnpAllvarsId id;

	public ViewSnpAllvars() {
	}

	public ViewSnpAllvars(ViewSnpAllvarsId id) {
		this.id = id;
	}

	public ViewSnpAllvarsId getId() {
		return this.id;
	}

	public void setId(ViewSnpAllvarsId id) {
		this.id = id;
	}

}
