package org.irri.iric.portal.genotype.views;

// Generated Jul 31, 2014 6:00:11 PM by Hibernate Tools 3.4.0.CR1

/**
 * ViewCount2linesMismatch generated by hbm2java
 */
public class ViewCount2linesMismatch implements java.io.Serializable {

	private ViewCount2linesMismatchId id;

	public ViewCount2linesMismatch() {
	}

	public ViewCount2linesMismatch(ViewCount2linesMismatchId id) {
		this.id = id;
	}

	public ViewCount2linesMismatchId getId() {
		return this.id;
	}

	public void setId(ViewCount2linesMismatchId id) {
		this.id = id;
	}

}
