package org.irri.iric.portal.genotype.views;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;

// Generated Jul 10, 2014 12:01:30 PM by Hibernate Tools 3.4.0.CR1

/**
 * ViewSnpAllvarsId generated by hbm2java
 */
@Entity @IdClass(ViewSnpAllvarsId.class)
public class ViewSnpAllvarsId implements java.io.Serializable {

	@Id
	private String varname;	
	@Id
	private Short chr;
	@Id
	private Long pos;
	@Id
	private String refnuc;
	@Id
	private String var1nuc;

	public ViewSnpAllvarsId() {
	}

	public ViewSnpAllvarsId(String varname, Short chr, Long pos, String refnuc,
			String var1nuc) {
		this.varname = varname;
		this.chr = chr;
		this.pos = pos;
		this.refnuc = refnuc;
		this.var1nuc = var1nuc;
	}

	public String getVarname() {
		return this.varname;
	}

	public void setVarname(String varname) {
		this.varname = varname;
	}

	public Short getChr() {
		return this.chr;
	}

	public void setChr(Short chr) {
		this.chr = chr;
	}

	public Long getPos() {
		return this.pos;
	}

	public void setPos(Long pos) {
		this.pos = pos;
	}

	public String getRefnuc() {
		return this.refnuc;
	}

	public void setRefnuc(String refnuc) {
		this.refnuc = refnuc;
	}

	public String getVar1nuc() {
		return this.var1nuc;
	}

	public void setVar1nuc(String var1nuc) {
		this.var1nuc = var1nuc;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewSnpAllvarsId))
			return false;
		ViewSnpAllvarsId castOther = (ViewSnpAllvarsId) other;

		return ((this.getVarname() == castOther.getVarname()) || (this
				.getVarname() != null && castOther.getVarname() != null && this
				.getVarname().equals(castOther.getVarname())))
				&& ((this.getChr() == castOther.getChr()) || (this.getChr() != null
						&& castOther.getChr() != null && this.getChr().equals(
						castOther.getChr())))
				&& ((this.getPos() == castOther.getPos()) || (this.getPos() != null
						&& castOther.getPos() != null && this.getPos().equals(
						castOther.getPos())))
				&& ((this.getRefnuc() == castOther.getRefnuc()) || (this
						.getRefnuc() != null && castOther.getRefnuc() != null && this
						.getRefnuc().equals(castOther.getRefnuc())))
				&& ((this.getVar1nuc() == castOther.getVar1nuc()) || (this
						.getVar1nuc() != null && castOther.getVar1nuc() != null && this
						.getVar1nuc().equals(castOther.getVar1nuc())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getVarname() == null ? 0 : this.getVarname().hashCode());
		result = 37 * result
				+ (getChr() == null ? 0 : this.getChr().hashCode());
		result = 37 * result
				+ (getPos() == null ? 0 : this.getPos().hashCode());
		result = 37 * result
				+ (getRefnuc() == null ? 0 : this.getRefnuc().hashCode());
		result = 37 * result
				+ (getVar1nuc() == null ? 0 : this.getVar1nuc().hashCode());
		return result;
	}

}
