package org.irri.iric.portal.genotype.views;

import javax.persistence.Entity;
import javax.persistence.Id;

// Generated Jul 10, 2014 8:32:19 PM by Hibernate Tools 3.4.0.CR1

/**
 * ViewSnpAllvarsPos generated by hbm2java
 */
@Entity
public class ViewSnpAllvarsPos implements java.io.Serializable {

	@Id
	private ViewSnpAllvarsPosId id;

	public ViewSnpAllvarsPos() {
	}

	public ViewSnpAllvarsPos(ViewSnpAllvarsPosId id) {
		this.id = id;
	}

	public ViewSnpAllvarsPosId getId() {
		return this.id;
	}

	public void setId(ViewSnpAllvarsPosId id) {
		this.id = id;
	}

}
