package org.irri.iric.portal.variety.views;

// Generated Jul 13, 2014 2:29:59 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;

import org.irri.iric.portal.genotype.views.ViewSnpAllvarsId;

/**
 * ViewDist3kId generated by hbm2java
 */
@Entity @IdClass(ViewDist3kId.class)
public class ViewDist3kId implements java.io.Serializable {

	@Id
	private String var1;
	@Id
	private String var2;
	@Id
	private String irisid1;
	@Id
	private String irisid2;
	@Id
	private BigDecimal dist;

	public ViewDist3kId() {
	}

	public ViewDist3kId(String var1, String var2, String irisid1,
			String irisid2, BigDecimal dist) {
		this.var1 = var1;
		this.var2 = var2;
		this.irisid1 = irisid1;
		this.irisid2 = irisid2;
		this.dist = dist;
	}

	public String getVar1() {
		return this.var1;
	}

	public void setVar1(String var1) {
		this.var1 = var1;
	}

	public String getVar2() {
		return this.var2;
	}

	public void setVar2(String var2) {
		this.var2 = var2;
	}

	public String getIrisid1() {
		return this.irisid1;
	}

	public void setIrisid1(String irisid1) {
		this.irisid1 = irisid1;
	}

	public String getIrisid2() {
		return this.irisid2;
	}

	public void setIrisid2(String irisid2) {
		this.irisid2 = irisid2;
	}

	public BigDecimal getDist() {
		return this.dist;
	}

	public void setDist(BigDecimal dist) {
		this.dist = dist;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewDist3kId))
			return false;
		ViewDist3kId castOther = (ViewDist3kId) other;

		return ((this.getVar1() == castOther.getVar1()) || (this.getVar1() != null
				&& castOther.getVar1() != null && this.getVar1().equals(
				castOther.getVar1())))
				&& ((this.getVar2() == castOther.getVar2()) || (this.getVar2() != null
						&& castOther.getVar2() != null && this.getVar2()
						.equals(castOther.getVar2())))
				&& ((this.getIrisid1() == castOther.getIrisid1()) || (this
						.getIrisid1() != null && castOther.getIrisid1() != null && this
						.getIrisid1().equals(castOther.getIrisid1())))
				&& ((this.getIrisid2() == castOther.getIrisid2()) || (this
						.getIrisid2() != null && castOther.getIrisid2() != null && this
						.getIrisid2().equals(castOther.getIrisid2())))
				&& ((this.getDist() == castOther.getDist()) || (this.getDist() != null
						&& castOther.getDist() != null && this.getDist()
						.equals(castOther.getDist())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getVar1() == null ? 0 : this.getVar1().hashCode());
		result = 37 * result
				+ (getVar2() == null ? 0 : this.getVar2().hashCode());
		result = 37 * result
				+ (getIrisid1() == null ? 0 : this.getIrisid1().hashCode());
		result = 37 * result
				+ (getIrisid2() == null ? 0 : this.getIrisid2().hashCode());
		result = 37 * result
				+ (getDist() == null ? 0 : this.getDist().hashCode());
		return result;
	}

}
