package org.irri.iric.portal.variety.views;

import javax.persistence.Entity;
import javax.persistence.Id;

// Generated Jul 13, 2014 2:29:59 PM by Hibernate Tools 3.4.0.CR1

/**
 * ViewDist3k generated by hbm2java
 */
@Entity
public class ViewDist3k implements java.io.Serializable {

	@Id
	private ViewDist3kId id;

	public ViewDist3k() {
	}

	public ViewDist3k(ViewDist3kId id) {
		this.id = id;
	}

	public ViewDist3kId getId() {
		return this.id;
	}

	public void setId(ViewDist3kId id) {
		this.id = id;
	}

}
